# Generated by Django 5.2.4 on 2025-07-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('sunlight', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('watering_frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_schedule', models.CharField(max_length=200)),
                ('sunlight_amount', models.CharField(max_length=200)),
                ('fertilizer_usage', models.CharField(max_length=200)),
                ('seasonal_care', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant')),
            ],
        ),
    ]
