# Generated by Django 5.2.4 on 2025-09-09 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerecommendation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='carerecommendation',
            name='fertilizer_usage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carerecommendation',
            name='seasonal_care',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carerecommendation',
            name='sunlight_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carerecommendation',
            name='watering_schedule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
