# Generated by Django 5.2.4 on 2025-09-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_carerecommendation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='region',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer_type',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('organic', 'Organic'), ('low-nitrogen', 'Low-nitrogen'), ('acidic', 'Acidic'), ('no', 'No fertilizer')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth',
            field=models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.CharField(max_length=100),
        ),
    ]
